### ISSUE TITLE
ksonnet seems to penalize breaking up large objects

### ISSUE THREAD

**Issue by chuckha** [ksonnet/ksonnet-lib#37]
Let's say I have this deployment:

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-sample-deployment
```
This translates nicely when I make it one object like so:
```jsonnet
deployment.new() +
deployment.mixin.metadata.name("my-sample-deployment")
```

But if I define my metadata first:
```jsonnet
local metadata = deployment.mixin.metadataType;
local sampleDeploymentMetadata = metadata.new() +
    metadata.name("my-sample-deployment");
```

I now only seem to have an awkward object to attach to the deployment like so:
```jsonnet
deployment.new() +
{
    "metadata": sampleDeploymentMetadata,
}
```

What do you think about supporting this kind of API:
```jsonnet
deployment.new() +
deployment.mixin.metadata(sampleDeploymentMetadata);
```

Alternatively tell me what I've missed :)

note: you may be wondering about this code
```jsonnet
deployment.new() +
sampleDeploymentMetadata
```
Well, this code yields:
```yaml
apiVersion: extensions/v1beta1
kind: Deployment
name: my-sample-deployment
```
