### ISSUE TITLE
Some labels keys are dropped from deployment meta to replica set

### ISSUE THREAD

**Issue by seryl** [ksonnet/ksonnet-lib#87]
It appears that some keys from map labels which are using `deployment.mixin.metadata.labels` get dropped for it's child replicaset.

Example:

```jsonld
local k = import "ksonnet.beta.2/k.libsonnet";

local container = k.extensions.v1beta1.deployment.mixin.spec.template.spec.containersType;
local containerPort = container.portsType;
local deployment = k.extensions.v1beta1.deployment;

local containerImage = "nginx";
local containerTag = "1.13.7-alpine";

local staticHttp =
  local targetPort = 80;
  container.new(containerImage, containerTag) +
  container.ports(containerPort.newNamed("http", targetPort));

{
  defaultConfig:: {
    limits: {memory: "200Mi", cpu: "100m"},
    labels: {tier: "web", example: "ok", aardvark: "ok"},
  },

  deployment(app, labels, limits)::
    local comboLabels = std.mergePatch(self.defaultConfig.labels, {amazing: app});

    deployment.new("nginx", 3, staticHttp, self.defaultConfig) +
      deployment.mixin.metadata.labels(comboLabels) + {testing: comboLabels},
}.deployment('awesome', {}, {})
```

Output:

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    aardvark: ok
    amazing: awesome
    example: ok
    tier: web
  name: nginx
spec:
  replicas: 3
  template:
    metadata:
      labels:
        labels:
          aardvark: ok
          example: ok
          tier: web
        limits:
          cpu: 100m
          memory: 200Mi
    spec:
      containers:
        - image: 1.13.7-alpine
          name: nginx
          ports:
            - containerPort: 80
              name: http
testing:
  aardvark: ok
  amazing: awesome
  example: ok
  tier: web
```

Notice: the `amazing` key is dropped from the replicaset labels.

I'm still digging into why this is happening, but it appears to be with the library.

Both [jsonnet](https://github.com/google/jsonnet) and [go-jsonnet](https://github.com/google/go-jsonnet) are producing the same incorrect output.
